---
galaxy_info:
  author: infrastructure-team
  description: Mount an Active Directory authenticated CIFS share
  license: proprietary
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "10"
dependencies: []

